### ISSUE TITLE
Error during install 

### ISSUE THREAD

**Issue by nesergen** [avxsynth/avxsynth#109]
Durin executing command   " ./configure && make " I have Error:

libtool: compile:  g++ -DPACKAGE_NAME=\"avxsynth\" -DPACKAGE_TARNAME=\"avxsynth\" -DPACKAGE_VERSION=\"4.0\" "-DPACKAGE_STRING=\"avxsynth 4.0\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"avxsynth\" -DVERSION=\"4.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -I../../include -I/usr/local/include -g -O2 -MT src/libavxffms2_la-videoutils.lo -MD -MP -MF src/.deps/libavxffms2_la-videoutils.Tpo -c src/videoutils.cpp  -fPIC -DPIC -o src/.libs/libavxffms2_la-videoutils.o
src/videoutils.cpp: In function 'BCSType GuessCSType(PixelFormat)':
src/videoutils.cpp:128:27: error: 'av_pix_fmt_desc_get' was not declared in this scope
src/videoutils.cpp: In function 'LossAttributes CalculateLoss(PixelFormat, PixelFormat)':
src/videoutils.cpp:157:62: error: 'av_pix_fmt_desc_get' was not declared in this scope
src/videoutils.cpp: At global scope:
src/videoutils.cpp:237:45: error: 'VP8' was not declared in this scope
src/videoutils.cpp:237:48: error: 'FFMS_ID' was not declared in this scope
make[1]: *** [src/libavxffms2_la-videoutils.lo] Error 1
make[1]: Leaving directory `/home/sergen/Загрузки/avxsynth-master/plugins/avxffms2'
make: *** [all-recursive] Error 1

what it is meaning ?

**Comment by nesergen** [comment]
I have used your link. Installation has been performed well. But I can`t find the AVXEdit file in "./avxsynth/apps/AVXEdit/" folder and can`t to start the programm.

**Comment by kaefert** [comment]
AVXEdit is non functional, you only can use avxsynth as a frameserver. use whatever text editor you like and then use mpv (like mplayer) to preview or ffmpeg to encode the result.

**Comment by nesergen** [comment]
I try to stabilise my video using following script:

```
LoadPlugin("Depan.dll")
LoadPlugin("DeGrainMedian.dll")
DirectShowSource("/home/sergen/SAM_3255.MP4")
M=DepanEstimate(trust=3) # спецклип M с данными по движению
DepanInterleave(data=M, prev=1, next=1) # утроенное число кадров
#DeGrainMedian() # некоторый шумопонижающий фильтр
Selectevery(3,1) # выделим из каждых трех один кадр
Weave()
```
But error is occure:

```
:~$ ffmpeg ~/avxsynth/motion.avs -vcodec libx264 -b 360k /avxsynth/StabilisedMovie.mp4
ffmpeg version N-69031-g365ef88 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jan 12 2015 19:07:50 with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
  configuration: --enable-gpl --enable-version3 --enable-avresample --enable-pic --enable-avisynth
  libavutil      54. 16.100 / 54. 16.100
  libavcodec     56. 20.100 / 56. 20.100
  libavformat    56. 18.101 / 56. 18.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5.  7.100 /  5.  7.100
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[NULL @ 0x23961c0] Unable to find a suitable output format for '/home/sergen/avxsynth/motion.avs'
/home/sergen/avxsynth/motion.avs: Invalid argument

```

**Comment by kaefert** [comment]
you need to use an "-i" to tell ffmpeg that the avs script is the input.
so:
$ ffmpeg -i ~/avxsynth/motion.avs -vcodec libx264 -b 360k /avxsynth/StabilisedMovie.mp4

**Comment by nesergen** [comment]
you right!
But it is another question. How can I import plugins to the avxsynth? I think a standard '.dll' not work on linux.

**Comment by kaefert** [comment]
nope, those dll's won't work with avxsynth. I've never used plugins (besides ffms2 which is included) with avxsynth.

My advice: use avisynth with wine if you need those plugins.

But maybe somebody else can give a better answer on how to get plugins like Depan & DeGrainMedian into Avxsynth, I don't know how - sorry.

**Comment by nesergen** [comment]
OK! Than, what can the linux avxsynth to do if it can`t to use plugins?

**Comment by kaefert** [comment]
Well, all those built in functions. Like:
http://avisynth.nl/index.php/Trim
http://avisynth.nl/index.php/BlankClip
http://avisynth.nl/index.php/ChangeFPS
http://avisynth.nl/index.php/Internal_functions

And of course any plugins that you can find in a pure *.avsi form (without *.dll)
like most of these:
http://avisynth.nl/index.php/Shared_functions

**Comment by nesergen** [comment]
thanks a lot !

**Comment by qyot27** [comment]
The few plugins that were apparently ported should just autoload, since when you install them they should be going into /usr/local/lib/avxsynth (or so I assume; I've never really messed with them).

[DePan was ported, though.](https://github.com/btb/depan)  I've never tried building it, though.

I've never had luck getting .avsi scripts to work (the classic example being FFMS2.avsi, which provides a familiar unified 'FFmpegSource2' function for those of us that remember using the original FFmpegSource - never got FFMS2.avsi to work right with AvxSynth).

**Comment by kaefert** [comment]
oh! I see.. well I never tried it, I just assumed that avsi plugins should work since their simply avs scripts that avxsynth should be able to interpret.

While we're talking about plugins - whenever I need to deinterlace some input I switch to avisynth via wine again since the best deinterlacer I've seen so far is 
http://avisynth.nl/index.php/QTGMC
which needs tons of *.dll dependencies to work - is there any advanced deinterlacer like that for Avxsynth?

**Comment by qyot27** [comment]
The only one that got ported was [Decomb](http://rationalqm.us/decomb/decombnew.html), http://mujintou.org.uk/projects/decomb.zip (linked directly to source package since the website is otherwise down; it would probably be a good idea to mirror that thing somewhere before it disappears completely).

It seems to be targeted at 64-bit, supposedly has issues with 32-bit (but I've never tried).  I've not used Decomb for IVTC in a very, very long time (I switched to TIVTC nearly a decade ago), but it was one of the first precise IVTC solutions available.  For really tricky sources, you could probably run YATTA in Wine to get the hinting and overrides and then possibly be able to use the overrides file with the native AvxSynth/Decomb combo.

**Comment by kaefert** [comment]
hmm, well as far as I understand decombing (detecting combs and trying to mask them) it is a very much inferior concept to good deinterlacing like QTGMC where both fields are used as base for new frames and the missing information is deducted by investigating the movement in the video.

decombing could be interesting for material badly cut together from different interlaced and progressive video - but I never had that problem yet.

**Comment by qyot27** [comment]
You're getting your terminology mixed up.  Some of it not unreasonable, since the Decomb package has a bit of a misleading name.  Usually when discussing AviSynth filters, field matchers and deinterlacers are considered to be in different categories, but outside of that they're often/usually lumped together (because yes, a field matcher removes interlacing, and thus is technically a 'deinterlacer').

See http://en.wikipedia.org/wiki/Deinterlacing#Field_combination_deinterlacing
What Decomb (actually, Telecide and Decimate) and TIVTC (TFM and TDecimate) do are the last two bullet points in that list (Inverse telecine and Telecide-style algorithms).  To quote,

>Unlike most other deinterlacing methods, when it works, inverse telecine can perfectly recover the original progressive video stream.

The caveat is that the user needs to know the cadence to configure the field matcher, and mismatches can happen (these can then be handed off to a standard deinterlacer or interpolator to do postprocessing).  Using manual overrides - why I mentioned YATTA - allows the user to make sure the matches are as accurate as they possibly can be, at the cost of being extremely tedious.  The easiest cadence is the canonical definition of interlacing: 1 frame = 2 fields, with no inter-frame bleedover and no funky decimating needed.  This would be the (assumed) case for NTSC and PAL TV in their native regions.

And of course, none of this is necessary with soft pulldown, which just requires that you remove or ignore the flagging.  Thankfully, most things like Hollywood movies use soft pulldown; it's the TV collections or foreign (NTSC stuff on PAL or vice-versa) content, or an irritatingly high number (read: nearly all of them) of anime DVDs from the late 90s-00s that use hard telecine or are stored interlaced.  It's only been recently that that last case finally started to use soft pulldown more often.


Using stuff like QTGMC is very often a desire to not have to mess with all of that theory and just set it to a given preset and have it 'just work'.  Not because field matching is inferior, but because it requires more of the user and can be less convenient.

**Comment by kaefert** [comment]
oh. okey. didn't know that, thanks :+1: 
Though I don't think that the material where I needed a deinterlacer - which came from ancient cameras that recorded to analog video 8 cassettes - would have benefited from reverse telecine - it truly only stored half of every frame to the tape - no telecine involved.

And for that material QTGMC seemed to give me the best results. I don't do too much with TV-recordings.

**Comment by qyot27** [comment]
The only things that make field matching specific to inverse telecine is the particular cadence type and the decimation.  Remove the decimate step and use a [2:2 cadence](http://en.wikipedia.org/wiki/Telecine#2:2_pulldown) and it's a simple frame reconstruction.  In this regard, consumer video cameras (camcorders and DV, although DV uses a different field order) and television match.

**Comment by kaefert** [comment]
hmm.. If 24p material is sped up by 4% and is aired with 50Hz (50 fields per second = 25 frames per second) isn't there sort of like nothing left to be done? there shouldn't be any visible artifacts since every 2 fields sent are both part of the same frame (read "same moment in time") so you shouldn't get any combs or anything?

the problem I solved with QTGMC was that every frame I read from the tape contains 2 fields from 2 different "moments in time" and the next frame read from the tape contains the next 2 "moments in time" recorded - therefore I do need to reconstruct the other half of every "moment in time" which QTGMC does very well by investigating movement in the picture.

Is that what you call "frame reconstruction"? Can the decomb plugin you linked a few comments above do that in a similar powerful way as QTGMC? Or is it more like "Bob" which simply displays every line twice which gives very inferior quality compared to QTGMC.

**Comment by qyot27** [comment]
>hmm.. If 24p material is sped up by 4% and is aired with 50Hz (50 fields per second = 25 frames per second) isn't there sort of like nothing left to be done? there shouldn't be any visible artifacts since every 2 fields sent are both part of the same frame (read "same moment in time") so you shouldn't get any combs or anything?

After field matching, yes.  As I said, that's the cleanest scenario to run into.

>the problem I solved with QTGMC was that every frame I read from the tape contains 2 fields from 2 different "moments in time" and the next frame read from the tape contains the next 2 "moments in time" recorded - therefore I do need to reconstruct the other half of every "moment in time" which QTGMC does very well by investigating movement in the picture.
>
>Is that what you call "frame reconstruction"? Can the decomb plugin you linked a few comments above do that in a similar powerful way as QTGMC?

No, I said 'frame reconstruction' simply as the filter's abilty to join the two fields back together into a single frame.  Where those fields come from (the previous frame, current frame, or the next frame) has to do with the cadence.  Using overrides can allow the user to force the matches to a different pattern, but it's tedious if it happens a lot.  And some cases (like the top and bottom halves of the image being from different frames) can be too much even for a field matcher, at least not without the help of other types of repair plugins.  Thankfully, I've never had to deal with a situation like that.

>Or is it more like "Bob" which simply displays every line twice which gives very inferior quality compared to QTGMC.

It's not a bobber.



And for whatever reason, now FFMS2.avsi is working for me with AvxSynth.  Hrmm.
