### ISSUE TITLE
avxsynth hangs on first FFVideoSource() call

### ISSUE THREAD

**Issue by kaefert** [avxsynth/avxsynth#110]
Hi there!

I've installed avxsynth on another laptop the same way I did last time (documented @ https://github.com/avxsynth/avxsynth/issues/105 )

But now on this laptop a simple version() avs script works, but as soon as I try to load any video stream with FFVideoSource the processing hangs without outputing any frames or any errors, using no resources. (both with mpv player and ffmpeg encoding)

It hangs also if the *.ffindex file is already existing, and also if I just call the FFIndex() function from within avxsynth instead of FFVideoSource(). No *.ffindex are created by avxsynth in the process.

It also doesn't matter if the given string is a valid path.
FFVideoSource("xx")
hangs just the same as
FFVideoSource("~/Videos/sample.mp4")

How can I debug this problem? please help. I think the last time I used avxsynth it was Linux Mint 16 too, this laptop has Mint 16 installed. So I'm guessing the difference is something that changed in the code contained in one of the used git-repositories..

**Comment by kaefert** [comment]
Is this something that needs to be fixed in Avxsynth or in FFMS2?

Is it lots of work, does something need to be redesigned, or can this one call causing this deadlock easily be moved somewhere else to avoid that deadlock?

**Comment by qyot27** [comment]
It can be fixed by not using a shared FFmpeg to build FFMS2.  Either switch to only static builds, or build FFmpeg two different ways: a static one (preferably trimmed down to just the essentials) for FFMS2 installed to a custom prefix that never touches the rest of the system, and a shared one for the system-wide stuff.  Shared libraries acting as circular dependencies is the stuff nightmares are made of.

>do you mind telling me what the c_plugin branch / version of ffms2 is for? where are the differences to the default master? (I couldn't find a quick answer by googling)

The c_plugin branch originated because it's used to build the C-interface version of the AviSynth plugin.  Although it can also build VapourSynth and AvxSynth plugins.  The difference from master is that master doesn't build AviSynth (C++ or C) or AvxSynth plugin interfaces into the library, and the c_plugin's build system isn't based on autotools.

**Comment by avxsynth-testing** [comment]
It's worth nothing that this can only occur if someone registers a avformat mutex, which is not the typical case, e.g. in the ffmpeg application. As long as AviSynth scripts are only opened on a single thread, it is not necessary to lock avformat in the AviSynth demuxer. This issue is not specific to AvxSynth, as pretty much all of AviSynth is thread unsafe.

Either way, there is no defect in AvxSynth.
